sudo: required

#install docker
services: 
 - docker

#execute logic
script:
 - echo "Hello students!"

after_success:
 # build all the docker files
 - docker build -t muktidoshi/zomato-master-client ./client
 - docker build -t muktidoshi/zomato-master-server ./server
 - docker build -t muktidoshi/zomato-master-nginx ./nginx

#log in docker
 -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#push to docker hub
 - docker push muktidoshi/zomato-master-client
 - docker push muktidoshi/zomato-master-server
 - docker push muktidoshi/zomato-master-nginx